name: CI-linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake ..
    - name: Build
      run: |
        cmake --build build
        ls -lh
